// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/EventService.proto

package com.example.system.grpc;

/**
 * Protobuf service {@code com.example.system.grpc.EventService}
 */
public  abstract class EventService
    implements com.google.protobuf.Service {
  protected EventService() {}

  public interface Interface {
    /**
     * <code>rpc trackEvent(.com.example.system.grpc.EventRequest) returns (.com.example.system.grpc.EventResponse);</code>
     */
    public abstract void trackEvent(
        com.google.protobuf.RpcController controller,
        com.example.system.grpc.EventRequest request,
        com.google.protobuf.RpcCallback<com.example.system.grpc.EventResponse> done);

  }

  public static com.google.protobuf.Service newReflectiveService(
      final Interface impl) {
    return new EventService() {
      @java.lang.Override
      public  void trackEvent(
          com.google.protobuf.RpcController controller,
          com.example.system.grpc.EventRequest request,
          com.google.protobuf.RpcCallback<com.example.system.grpc.EventResponse> done) {
        impl.trackEvent(controller, request, done);
      }

    };
  }

  public static com.google.protobuf.BlockingService
      newReflectiveBlockingService(final BlockingInterface impl) {
    return new com.google.protobuf.BlockingService() {
      public final com.google.protobuf.Descriptors.ServiceDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }

      public final com.google.protobuf.Message callBlockingMethod(
          com.google.protobuf.Descriptors.MethodDescriptor method,
          com.google.protobuf.RpcController controller,
          com.google.protobuf.Message request)
          throws com.google.protobuf.ServiceException {
        if (method.getService() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "Service.callBlockingMethod() given method descriptor for " +
            "wrong service type.");
        }
        switch(method.getIndex()) {
          case 0:
            return impl.trackEvent(controller, (com.example.system.grpc.EventRequest)request);
          default:
            throw new java.lang.AssertionError("Can't get here.");
        }
      }

      public final com.google.protobuf.Message
          getRequestPrototype(
          com.google.protobuf.Descriptors.MethodDescriptor method) {
        if (method.getService() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "Service.getRequestPrototype() given method " +
            "descriptor for wrong service type.");
        }
        switch(method.getIndex()) {
          case 0:
            return com.example.system.grpc.EventRequest.getDefaultInstance();
          default:
            throw new java.lang.AssertionError("Can't get here.");
        }
      }

      public final com.google.protobuf.Message
          getResponsePrototype(
          com.google.protobuf.Descriptors.MethodDescriptor method) {
        if (method.getService() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "Service.getResponsePrototype() given method " +
            "descriptor for wrong service type.");
        }
        switch(method.getIndex()) {
          case 0:
            return com.example.system.grpc.EventResponse.getDefaultInstance();
          default:
            throw new java.lang.AssertionError("Can't get here.");
        }
      }

    };
  }

  /**
   * <code>rpc trackEvent(.com.example.system.grpc.EventRequest) returns (.com.example.system.grpc.EventResponse);</code>
   */
  public abstract void trackEvent(
      com.google.protobuf.RpcController controller,
      com.example.system.grpc.EventRequest request,
      com.google.protobuf.RpcCallback<com.example.system.grpc.EventResponse> done);

  public static final
      com.google.protobuf.Descriptors.ServiceDescriptor
      getDescriptor() {
    return com.example.system.grpc.EventServiceOuterClass.getDescriptor().getServices().get(0);
  }
  public final com.google.protobuf.Descriptors.ServiceDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }

  public final void callMethod(
      com.google.protobuf.Descriptors.MethodDescriptor method,
      com.google.protobuf.RpcController controller,
      com.google.protobuf.Message request,
      com.google.protobuf.RpcCallback<
        com.google.protobuf.Message> done) {
    if (method.getService() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "Service.callMethod() given method descriptor for wrong " +
        "service type.");
    }
    switch(method.getIndex()) {
      case 0:
        this.trackEvent(controller, (com.example.system.grpc.EventRequest)request,
          com.google.protobuf.RpcUtil.<com.example.system.grpc.EventResponse>specializeCallback(
            done));
        return;
      default:
        throw new java.lang.AssertionError("Can't get here.");
    }
  }

  public final com.google.protobuf.Message
      getRequestPrototype(
      com.google.protobuf.Descriptors.MethodDescriptor method) {
    if (method.getService() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "Service.getRequestPrototype() given method " +
        "descriptor for wrong service type.");
    }
    switch(method.getIndex()) {
      case 0:
        return com.example.system.grpc.EventRequest.getDefaultInstance();
      default:
        throw new java.lang.AssertionError("Can't get here.");
    }
  }

  public final com.google.protobuf.Message
      getResponsePrototype(
      com.google.protobuf.Descriptors.MethodDescriptor method) {
    if (method.getService() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "Service.getResponsePrototype() given method " +
        "descriptor for wrong service type.");
    }
    switch(method.getIndex()) {
      case 0:
        return com.example.system.grpc.EventResponse.getDefaultInstance();
      default:
        throw new java.lang.AssertionError("Can't get here.");
    }
  }

  public static Stub newStub(
      com.google.protobuf.RpcChannel channel) {
    return new Stub(channel);
  }

  public static final class Stub extends com.example.system.grpc.EventService implements Interface {
    private Stub(com.google.protobuf.RpcChannel channel) {
      this.channel = channel;
    }

    private final com.google.protobuf.RpcChannel channel;

    public com.google.protobuf.RpcChannel getChannel() {
      return channel;
    }

    public  void trackEvent(
        com.google.protobuf.RpcController controller,
        com.example.system.grpc.EventRequest request,
        com.google.protobuf.RpcCallback<com.example.system.grpc.EventResponse> done) {
      channel.callMethod(
        getDescriptor().getMethods().get(0),
        controller,
        request,
        com.example.system.grpc.EventResponse.getDefaultInstance(),
        com.google.protobuf.RpcUtil.generalizeCallback(
          done,
          com.example.system.grpc.EventResponse.class,
          com.example.system.grpc.EventResponse.getDefaultInstance()));
    }
  }

  public static BlockingInterface newBlockingStub(
      com.google.protobuf.BlockingRpcChannel channel) {
    return new BlockingStub(channel);
  }

  public interface BlockingInterface {
    public com.example.system.grpc.EventResponse trackEvent(
        com.google.protobuf.RpcController controller,
        com.example.system.grpc.EventRequest request)
        throws com.google.protobuf.ServiceException;
  }

  private static final class BlockingStub implements BlockingInterface {
    private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
      this.channel = channel;
    }

    private final com.google.protobuf.BlockingRpcChannel channel;

    public com.example.system.grpc.EventResponse trackEvent(
        com.google.protobuf.RpcController controller,
        com.example.system.grpc.EventRequest request)
        throws com.google.protobuf.ServiceException {
      return (com.example.system.grpc.EventResponse) channel.callBlockingMethod(
        getDescriptor().getMethods().get(0),
        controller,
        request,
        com.example.system.grpc.EventResponse.getDefaultInstance());
    }

  }

  // @@protoc_insertion_point(class_scope:com.example.system.grpc.EventService)
}

