version: "3"
services:
  eureka:
    build: ../eureka-service
    ports:
    - "8761:8761"
    environment:
      eureka.client.registerWithEureka: "false"
      eureka.client.fetchRegistry: "false"
      server.port: 8761
  user:
    build: ./
    ports:
    - "8070:8070"
    environment:
      eureka.client.serviceUrl.defaultZone: http://eureka:8761/eureka/
      spring.application.name: userservice
      server.port: 8070
      restart: on-failure
      grpc.eureka.service-id: systemevents