// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/EventService.proto

package com.example.demo.grpc;

public final class EventServiceOuterClass {
  private EventServiceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_demo_grpc_EventRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_demo_grpc_EventRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_demo_grpc_EventResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_demo_grpc_EventResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030proto/EventService.proto\022\025com.example." +
      "demo.grpc\"s\n\014EventRequest\022\n\n\002id\030\001 \001(\005\022\021\n" +
      "\ttimestamp\030\002 \001(\t\022\023\n\013serviceName\030\003 \001(\t\022\016\n" +
      "\006userId\030\004 \001(\t\022\017\n\007request\030\005 \001(\t\022\016\n\006status" +
      "\030\006 \001(\005\"\037\n\rEventResponse\022\016\n\006status\030\001 \001(\t2" +
      "g\n\014EventService\022W\n\ntrackEvent\022#.com.exam" +
      "ple.demo.grpc.EventRequest\032$.com.example" +
      ".demo.grpc.EventResponseB\"\n\025com.example." +
      "demo.grpcP\001Z\004grpc\210\001\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_example_demo_grpc_EventRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_example_demo_grpc_EventRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_demo_grpc_EventRequest_descriptor,
        new java.lang.String[] { "Id", "Timestamp", "ServiceName", "UserId", "Request", "Status", });
    internal_static_com_example_demo_grpc_EventResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_example_demo_grpc_EventResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_demo_grpc_EventResponse_descriptor,
        new java.lang.String[] { "Status", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
